name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        command: buildozer android debug
