name: Build Kivy APK

on:
  push:
    branches: [ main ]
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # 🔥 FIX QUI

    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
    - uses: actions/checkout@v4

    - name: Cache buildozer
      uses: actions/cache@v4
      with:
        path: |
          ~/.buildozer
          ~/.gradle
        key: ${{ runner.os }}-buildozer

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Install deps
      run: |
        sudo apt install -y \
          python3-pip unzip wget \
          autoconf automake libtool \
          pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake ninja-build

    - name: Install Python deps
      run: |
        pip install --upgrade pip
        pip install buildozer cython==0.29.36 python-for-android==2024.1.21

    - name: Setup Android SDK
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-11076708_latest.zip

        mv cmdline-tools latest

    - name: Add SDK to PATH
      run: |
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

    - name: Accept licenses (manual)
      run: |
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_SDK_ROOT/licenses/android-sdk-license

    - name: Install SDK
      run: |
        sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

    - name: Fix Buildozer licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        cp -r $ANDROID_SDK_ROOT/licenses/* ~/.buildozer/android/platform/android-sdk/licenses/ || true

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: bin/*.apk
