name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk wget

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mv cmdline-tools cmdline-tools/latest

        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Install SDK packages
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Build APK
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        command: buildozer android debug
